name: "test"
on:
  push:

jobs:
  push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash {0}
      - name: test
        run: |
          date
          exit 1
          date # ここまで到達させたい
